field: e03553d9-f79c-426d-8435-107fab9b1398
fieldLayouts:
  930d380f-b56c-43e9-af4b-1704a09b72b4:
    tabs:
      -
        fields:
          18711718-a330-484b-8cbc-ca5eb50ac28e:
            required: false
            sortOrder: 4
          24a3d454-328a-4ef5-ad67-df94591eaa33:
            required: false
            sortOrder: 3
          2a27abee-b26b-49cb-b34c-063ad3a3cafd:
            required: false
            sortOrder: 1
          494a4e3c-7c0f-44d7-b4bf-261275d342bd:
            required: false
            sortOrder: 2
        name: Content
        sortOrder: 1
fields:
  18711718-a330-484b-8cbc-ca5eb50ac28e:
    contentColumnType: text
    fieldGroup: null
    handle: tekstovoeOpisanie
    instructions: ''
    name: 'Текстовое описание'
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Standard.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  24a3d454-328a-4ef5-ad67-df94591eaa33:
    contentColumnType: string
    fieldGroup: null
    handle: fotografii
    instructions: ''
    name: Фотографии
    searchable: true
    settings:
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:2067eae4-e93b-402f-b233-627ae3d6c0fa'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: 'Добавить фотографии'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:1a5b16e2-10cb-4cc8-93b0-77bcdac8e2dc'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: ''
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  2a27abee-b26b-49cb-b34c-063ad3a3cafd:
    contentColumnType: text
    fieldGroup: null
    handle: nazvanie
    instructions: ''
    name: Название
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  494a4e3c-7c0f-44d7-b4bf-261275d342bd:
    contentColumnType: string
    fieldGroup: null
    handle: glavnoeIzobrazhenie
    instructions: ''
    name: 'Главное изображение'
    searchable: true
    settings:
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:2067eae4-e93b-402f-b233-627ae3d6c0fa'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: 'Добавить изображение'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:1a5b16e2-10cb-4cc8-93b0-77bcdac8e2dc'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: ''
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: blok
name: Блок
sortOrder: 1
