field: ab1fcc9b-956d-4e1c-8c1c-caac8a904b8b
fieldLayouts:
  1141f742-84e4-4202-8e07-8c006214978d:
    tabs:
      -
        fields:
          136baaee-ed5f-4e0c-b833-aea557f8b487:
            required: false
            sortOrder: 1
          370e2390-c0f9-4da8-8a1e-d94dae5fa094:
            required: false
            sortOrder: 2
        name: Content
        sortOrder: 1
fields:
  136baaee-ed5f-4e0c-b833-aea557f8b487:
    contentColumnType: text
    fieldGroup: null
    handle: nazvanie
    instructions: ''
    name: Название
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  370e2390-c0f9-4da8-8a1e-d94dae5fa094:
    contentColumnType: string
    fieldGroup: null
    handle: izobrazhenie
    instructions: ''
    name: Изображение
    searchable: true
    settings:
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:2067eae4-e93b-402f-b233-627ae3d6c0fa'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: 'Добавить изображение'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:2067eae4-e93b-402f-b233-627ae3d6c0fa'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: ''
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: parallaks
name: Параллакс
sortOrder: 4
