contentColumnType: boolean
fieldGroup: f1c98c1f-1d3a-4b88-9c23-84c01dc3d040
handle: menuOpenInNewTab
instructions: ''
name: 'Открыть в новом окне'
searchable: true
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
