contentColumnType: string
fieldGroup: cbd14a90-6792-4c0d-b7db-feba0d5ac542
handle: teamImage
instructions: ''
name: Фото
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:2067eae4-e93b-402f-b233-627ae3d6c0fa'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Добавить фото'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:2067eae4-e93b-402f-b233-627ae3d6c0fa'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: ''
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
