fieldLayouts:
  1639d838-af5f-478a-85e8-466abf8a3dc8:
    tabs:
      -
        fields:
          f9730cd3-95f7-40bf-888b-18ff07dba2bb:
            required: false
            sortOrder: 1
        name: Контент
        sortOrder: 1
handle: globalYoutube
name: Youtube
