fieldLayouts:
  68d995a9-5f9b-4e58-8b4a-ff38b30cccd3:
    tabs:
      -
        fields:
          6bc626eb-f69e-4a76-bae6-6f8b701b7b30:
            required: false
            sortOrder: 1
        name: Контент
        sortOrder: 1
handle: globalPhoneConsult
name: 'Консультация телефон'
