fieldLayouts:
  f6d9337e-41ef-4fe8-930e-32b7807657d1:
    tabs:
      -
        fields:
          f9730cd3-95f7-40bf-888b-18ff07dba2bb:
            required: false
            sortOrder: 1
        name: Контент
        sortOrder: 1
handle: globalEmail
name: Email
