fieldLayouts:
  2b51822a-5d4c-4e55-adef-5be939eb9646:
    tabs:
      -
        fields:
          6bc626eb-f69e-4a76-bae6-6f8b701b7b30:
            required: false
            sortOrder: 1
        name: Контент
        sortOrder: 1
handle: globalWhatsapp
name: Whatsapp
