enableVersioning: true
handle: gallery
name: Фотогаллерея
propagationMethod: all
siteSettings:
  25c86c4e-fa93-42c2-95c7-588f64bfb08f:
    enabledByDefault: true
    hasUrls: true
    template: gallery/index
    uriFormat: gallery
type: single
