enableVersioning: true
handle: home
name: Главная
propagationMethod: all
siteSettings:
  25c86c4e-fa93-42c2-95c7-588f64bfb08f:
    enabledByDefault: true
    hasUrls: true
    template: ''
    uriFormat: __home__
type: single
