enableVersioning: true
handle: oshibokNevestyVDenSvadBy
name: '5 ошибок невесты в день свадьбы'
propagationMethod: all
siteSettings:
  25c86c4e-fa93-42c2-95c7-588f64bfb08f:
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry
    uriFormat: 5_oshibok_nevesti_v_den_svadbi
type: single
