enableVersioning: true
handle: pravilKotoryeDolzhnySoblyudatGostiNaSvadBe
name: '10 правил, которые должны соблюдать гости на свадьбе'
propagationMethod: all
siteSettings:
  25c86c4e-fa93-42c2-95c7-588f64bfb08f:
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry
    uriFormat: 10_pravil_kotorie_dolzhni_soblyudat_gosti
type: single
