enableVersioning: true
handle: svadebnyeVedushchie
name: 'Как выбрать свадебного ведущего?'
propagationMethod: all
siteSettings:
  25c86c4e-fa93-42c2-95c7-588f64bfb08f:
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry
    uriFormat: kak_vibrat_svadebnogo_vedushego
type: single
