enableVersioning: true
handle: svadBaVTrendeBezStarykhTraditsiy
name: 'Свадьба в тренде - без старых традиций'
propagationMethod: all
siteSettings:
  25c86c4e-fa93-42c2-95c7-588f64bfb08f:
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry
    uriFormat: svadba_v_trende_bezh_starih_tradicii
type: single
