enableVersioning: true
handle: vazhnyeSovetyDlyaNevestyKakIzbezhatStressaPeredSvadBoy
name: 'Важные советы для невесты:  как избежать стресса перед свадьбой.'
propagationMethod: all
siteSettings:
  25c86c4e-fa93-42c2-95c7-588f64bfb08f:
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry
    uriFormat: vazhnie_soveti_dlya_nevesti
type: single
