enableVersioning: true
handle: video
name: Видео
propagationMethod: all
siteSettings:
  25c86c4e-fa93-42c2-95c7-588f64bfb08f:
    enabledByDefault: true
    hasUrls: true
    template: video/index
    uriFormat: video
type: single
